version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 007171156788.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t code-build .
      - docker tag code-build:latest 007171156788.dkr.ecr.us-east-2.amazonaws.com/code-build:latest
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 007171156788.dkr.ecr.us-east-2.amazonaws.com/code-build:latest
